-- ChaukeStudyTime database that will store user information and module information
CREATE DATABASE StudyTimeDatabase;

-- use statement
USE [StudyTimeDatabase];

-- creating tables for capturing user data
-- TABLE USER_REGISTRATION WILL REEGISTER USER INTO DATABASE
CREATE TABLE USER_REGISTRATIONS 
(
	USER_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	FIRSTNAME NVARCHAR(50) NOT NULL,
	LASTNAME NVARCHAR(100) NOT NULL,
	EMAIL NVARCHAR(150) NOT NULL,
	USERNAME NVARCHAR(8) NOT NULL UNIQUE,
	PASSWORD NVARCHAR(255) NOT NULL,
	
	
);

-- TABLE USER_MODULES WILL CAPTURE MODULE DETAILS
CREATE TABLE USER_MODULE 
(
	MODULE_ID INT IDENTITY(1,1) NOT NULL,
	MODULE_CODE NVARCHAR(50) NOT NULL,
	MODULE_NAME NVARCHAR(200) NOT NULL,
	NUMBER_OF_CREDITS INT NOT NULL,
	CLASS_HOURS_PER_WEEK INT NOT NULL,
	NUMBER_OF_WEEKS INT NOT NULL,
	START_DATE NVARCHAR(50) NOT NULL,
	END_DATE NVARCHAR(50) NOT NULL,
	USERNAME NVARCHAR(8) FOREIGN KEY REFERENCES USER_REGISTRATIONS(USERNAME) NOT NULL,
	selfStudy_hoursPerWeek NVARCHAR(100) NOT NULL,
	PRIMARY KEY (MODULE_ID, MODULE_CODE)
);

-- SELECT STATEMENTS TO VIEW OUTPUT
SELECT * FROM USER_REGISTRATIONS;
SELECT * FROM USER_MODULE;



